CREATE DATABASE IF NOT EXISTS ExpensesDB;

CREATE TABLE Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE Expenses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  amount FLOAT NOT NULL,
  date DATE NOT NULL,
  category VARCHAR(255) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES Users(id)
);
